<?php
                                                                                                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                                                                                                     * Add Custom Post Type "Kontak Informasi" inside Tutor LMS menu
                                                                                                                                                                                                                                                                                                                                                                     * 
                                                                                                                                                                                                                                                                                                                                                                     * @author Puji Ermanto <pujiermanto@gmail.com> | AKA Jhony Rotten
                                                                                                                                                                                                                                                                                                                                                                     * @version 1.3
                                                                                                                                                                                                                                                                                                                                                                     * @description Menambahkan post type khusus untuk menyimpan informasi kontak ke dalam submenu Tutor LMS di dashboard WordPress,
                                                                                                                                                                                                                                                                                                                                                                     * lengkap dengan input dinamis untuk negara dan alamat (textarea).
                                                                                                                                                                                                                                                                                                                                                                     */

                                                                                                                                                                                                                                                                                                                                                                    add_action('init', function () {
                                                                                                                                                                                                                                                                                                                                                                        $labels = array(
                                                                                                                                                                                                                                                                                                                                                                            'name'               => 'Kontak Informasi',
                                                                                                                                                                                                                                                                                                                                                                            'singular_name'      => 'Kontak Informasi',
                                                                                                                                                                                                                                                                                                                                                                            'menu_name'          => 'Kontak Informasi',
                                                                                                                                                                                                                                                                                                                                                                            'add_new'            => 'Tambah Informasi',
                                                                                                                                                                                                                                                                                                                                                                            'add_new_item'       => 'Tambah Kontak Baru',
                                                                                                                                                                                                                                                                                                                                                                            'edit_item'          => 'Edit Kontak',
                                                                                                                                                                                                                                                                                                                                                                            'view_item'          => 'Lihat Kontak',
                                                                                                                                                                                                                                                                                                                                                                            'all_items'          => 'Semua Kontak',
                                                                                                                                                                                                                                                                                                                                                                            'search_items'       => 'Cari Kontak',
                                                                                                                                                                                                                                                                                                                                                                            'not_found'          => 'Tidak ditemukan',
                                                                                                                                                                                                                                                                                                                                                                            'not_found_in_trash' => 'Tidak ditemukan di sampah'
                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                        $args = array(
                                                                                                                                                                                                                                                                                                                                                                            'labels'             => $labels,
                                                                                                                                                                                                                                                                                                                                                                            'public'             => false,
                                                                                                                                                                                                                                                                                                                                                                            'show_ui'            => true,
                                                                                                                                                                                                                                                                                                                                                                            'show_in_menu'       => 'tutor',
                                                                                                                                                                                                                                                                                                                                                                            'menu_position'      => 25,
                                                                                                                                                                                                                                                                                                                                                                            'menu_icon'          => 'dashicons-id-alt',
                                                                                                                                                                                                                                                                                                                                                                            'supports'           => array('title'),
                                                                                                                                                                                                                                                                                                                                                                            'has_archive'        => false,
                                                                                                                                                                                                                                                                                                                                                                            'rewrite'            => false,
                                                                                                                                                                                                                                                                                                                                                                            'capability_type'    => 'post'
                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                        register_post_type('kontak_informasi', $args);
                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                                                                                                     * Tambahkan Meta Box untuk input data kontak
                                                                                                                                                                                                                                                                                                                                                                     */
                                                                                                                                                                                                                                                                                                                                                                    add_action('add_meta_boxes', function () {
                                                                                                                                                                                                                                                                                                                                                                        add_meta_box(
                                                                                                                                                                                                                                                                                                                                                                            'kontak_informasi_meta_box',
                                                                                                                                                                                                                                                                                                                                                                            'Detail Kontak Informasi',
                                                                                                                                                                                                                                                                                                                                                                            'render_kontak_informasi_meta_box',
                                                                                                                                                                                                                                                                                                                                                                            'kontak_informasi',
                                                                                                                                                                                                                                                                                                                                                                            'normal',
                                                                                                                                                                                                                                                                                                                                                                            'default'
                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                                                                                                     * Render isi Meta Box
                                                                                                                                                                                                                                                                                                                                                                     */
                                                                                                                                                                                                                                                                                                                                                                    function render_kontak_informasi_meta_box($post)
                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                        wp_nonce_field('save_kontak_informasi', 'kontak_informasi_nonce');

                                                                                                                                                                                                                                                                                                                                                                        // Ambil data alamat per negara
                                                                                                                                                                                                                                                                                                                                                                        $alamat_negara = get_post_meta($post->ID, 'alamat_negara', true);
                                                                                                                                                                                                                                                                                                                                                                        $alamat_negara = is_array($alamat_negara) ? $alamat_negara : [];

                                                                                                                                                                                                                                                                                                                                                                        // Field lain
                                                                                                                                                                                                                                                                                                                                                                        $fields = [
                                                                                                                                                                                                                                                                                                                                                                            'email'     => 'Email',
                                                                                                                                                                                                                                                                                                                                                                            'telepon'   => 'No Telepon',
                                                                                                                                                                                                                                                                                                                                                                            'instagram' => 'Instagram',
                                                                                                                                                                                                                                                                                                                                                                            'twitter'   => 'Twitter (X)',
                                                                                                                                                                                                                                                                                                                                                                            'youtube'   => 'YouTube',
                                                                                                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                                                                                                        echo '<table class="form-table">';

                                                                                                                                                                                                                                                                                                                                                                        // === Bagian Negara + Alamat ===
                                                                                                                                                                                                                                                                                                                                                                        echo '<tr><th><label>Alamat per Negara</label></th><td>';
                                                                                                                                                                                                                                                                                                                                                                        echo '<div id="alamat-negara-wrapper">';

                                                                                                                                                                                                                                                                                                                                                                        if (!empty($alamat_negara)) {
                                                                                                                                                                                                                                                                                                                                                                            foreach ($alamat_negara as $item) {
                                                                                                                                                                                                                                                                                                                                                                                $negara = esc_attr($item['negara'] ?? '');
                                                                                                                                                                                                                                                                                                                                                                                $alamat = esc_textarea($item['alamat'] ?? '');
                                                                                                                                                                                                                                                                                                                                                                                echo '<div class="alamat-block" style="margin-bottom:15px;border:1px solid #ddd;padding:10px;border-radius:6px;">';
                                                                                                                                                                                                                                                                                                                                                                                echo '<select name="alamat_negara[][negara]" style="width:200px;margin-bottom:6px;">';
                                                                                                                                                                                                                                                                                                                                                                                echo negara_options($negara);
                                                                                                                                                                                                                                                                                                                                                                                echo '</select><br>';
                                                                                                                                                                                                                                                                                                                                                                                echo '<textarea name="alamat_negara[][alamat]" rows="3" style="width:100%;resize:vertical;">' . $alamat . '</textarea>';
                                                                                                                                                                                                                                                                                                                                                                                echo '<br><button type="button" class="button remove-alamat">Hapus</button>';
                                                                                                                                                                                                                                                                                                                                                                                echo '</div>';
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                            echo '<div class="alamat-block" style="margin-bottom:15px;border:1px solid #ddd;padding:10px;border-radius:6px;">';
                                                                                                                                                                                                                                                                                                                                                                            echo '<select name="alamat_negara[][negara]" style="width:200px;margin-bottom:6px;">';
                                                                                                                                                                                                                                                                                                                                                                            echo negara_options('');
                                                                                                                                                                                                                                                                                                                                                                            echo '</select><br>';
                                                                                                                                                                                                                                                                                                                                                                            echo '<textarea name="alamat_negara[][alamat]" rows="3" style="width:100%;resize:vertical;"></textarea>';
                                                                                                                                                                                                                                                                                                                                                                            echo '<br><button type="button" class="button remove-alamat">Hapus</button>';
                                                                                                                                                                                                                                                                                                                                                                            echo '</div>';
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        echo '</div>';
                                                                                                                                                                                                                                                                                                                                                                        echo '<button type="button" class="button" id="add-alamat-negara">+ Tambah Negara & Alamat</button>';
                                                                                                                                                                                                                                                                                                                                                                        echo '<p class="description">Pilih negara dan isi alamat lengkap. Bisa menambahkan beberapa negara.</p>';
                                                                                                                                                                                                                                                                                                                                                                        echo '</td></tr>';

                                                                                                                                                                                                                                                                                                                                                                        // === Field Kontak Lain ===
                                                                                                                                                                                                                                                                                                                                                                        foreach ($fields as $key => $label) {
                                                                                                                                                                                                                                                                                                                                                                            $value = get_post_meta($post->ID, $key, true);
                                                                                                                                                                                                                                                                                                                                                                            echo '<tr>';
                                                                                                                                                                                                                                                                                                                                                                            echo '<th><label for="' . esc_attr($key) . '">' . esc_html($label) . '</label></th>';
                                                                                                                                                                                                                                                                                                                                                                            echo '<td><input type="text" id="' . esc_attr($key) . '" name="' . esc_attr($key) . '" value="' . esc_attr($value) . '" class="regular-text"></td>';
                                                                                                                                                                                                                                                                                                                                                                            echo '</tr>';
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        echo '</table>';

                                                                                                                                                                                                                                                                                                                                                                        // === Script Dinamis ===
                                                                                                                                                                                                                                                                                                                                                                    ?>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const wrapper = document.getElementById('alamat-negara-wrapper');
            const addBtn = document.getElementById('add-alamat-negara');

            addBtn.addEventListener('click', function() {
                const div = document.createElement('div');
                div.className = 'alamat-block';
                div.style.cssText = 'margin-bottom:15px;border:1px solid #ddd;padding:10px;border-radius:6px;';

                div.innerHTML = `
                <select name="alamat_negara[][negara]" style="width:200px;margin-bottom:6px;">
                    <?php echo str_replace("\n", '', addslashes(negara_options(''))); ?>
                </select><br>
                <textarea name="alamat_negara[][alamat]" rows="3" style="width:100%;resize:vertical;"></textarea>
                <br><button type="button" class="button remove-alamat">Hapus</button>
            `;

                wrapper.appendChild(div);
            });

            wrapper.addEventListener('click', function(e) {
                if (e.target.classList.contains('remove-alamat')) {
                    e.target.closest('.alamat-block').remove();
                }
            });
        });
    </script>
    Pilihan dropdown negaraSimpan data meta box<?php
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                                                                                                     * Pilihan dropdown negara
                                                                                                                                                                                                                                                                                                                                                                     */
                                                                                                                                                                                                                                                                                                                                                                    function negara_options($selected = '')
                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                        $countries = [
                                                                                                                                                                                                                                                                                                                                                                            '' => 'Pilih Negara',
                                                                                                                                                                                                                                                                                                                                                                            'Indonesia' => 'Indonesia',
                                                                                                                                                                                                                                                                                                                                                                            'Japan' => 'Japan',
                                                                                                                                                                                                                                                                                                                                                                            'Malaysia' => 'Malaysia',
                                                                                                                                                                                                                                                                                                                                                                            'Singapore' => 'Singapore',
                                                                                                                                                                                                                                                                                                                                                                            'Thailand' => 'Thailand',
                                                                                                                                                                                                                                                                                                                                                                            'Vietnam' => 'Vietnam',
                                                                                                                                                                                                                                                                                                                                                                            'China' => 'China',
                                                                                                                                                                                                                                                                                                                                                                            'South Korea' => 'South Korea',
                                                                                                                                                                                                                                                                                                                                                                            'USA' => 'USA',
                                                                                                                                                                                                                                                                                                                                                                            'UK' => 'UK',
                                                                                                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                                                                                                        $html = '';
                                                                                                                                                                                                                                                                                                                                                                        foreach ($countries as $key => $label) {
                                                                                                                                                                                                                                                                                                                                                                            $sel = ($selected === $key) ? 'selected' : '';
                                                                                                                                                                                                                                                                                                                                                                            $html .= "<option value='{$key}' {$sel}>{$label}</option>";
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                        return $html;
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                                                                                                     * Simpan data meta box
                                                                                                                                                                                                                                                                                                                                                                     */
                                                                                                                                                                                                                                                                                                                                                                    add_action('save_post', function ($post_id) {
                                                                                                                                                                                                                                                                                                                                                                        if (!isset($_POST['kontak_informasi_nonce']) || !wp_verify_nonce($_POST['kontak_informasi_nonce'], 'save_kontak_informasi')) {
                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        // Simpan alamat per negara
                                                                                                                                                                                                                                                                                                                                                                        if (isset($_POST['alamat_negara']) && is_array($_POST['alamat_negara'])) {
                                                                                                                                                                                                                                                                                                                                                                            $alamat_negara = [];
                                                                                                                                                                                                                                                                                                                                                                            foreach ($_POST['alamat_negara'] as $item) {
                                                                                                                                                                                                                                                                                                                                                                                $negara = sanitize_text_field($item['negara'] ?? '');
                                                                                                                                                                                                                                                                                                                                                                                $alamat = sanitize_textarea_field($item['alamat'] ?? '');
                                                                                                                                                                                                                                                                                                                                                                                if ($negara && $alamat) {
                                                                                                                                                                                                                                                                                                                                                                                    $alamat_negara[] = compact('negara', 'alamat');
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                            update_post_meta($post_id, 'alamat_negara', $alamat_negara);
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        // Simpan field lain
                                                                                                                                                                                                                                                                                                                                                                        $fields = ['email', 'telepon', 'instagram', 'twitter', 'youtube'];
                                                                                                                                                                                                                                                                                                                                                                        foreach ($fields as $field) {
                                                                                                                                                                                                                                                                                                                                                                            if (isset($_POST[$field])) {
                                                                                                                                                                                                                                                                                                                                                                                update_post_meta($post_id, $field, sanitize_text_field($_POST[$field]));
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                    });
